insert into staff values('st00','Delors,Jacques');

insert into staff values('st01','Costain,William');

insert into staff values('st02','Hague,William');

insert into staff values('st03','Wogan,Terence');

insert into staff values('st04','Beethoven,LV');

insert into staff values('st05','Charles,HRHPrince');

insert into staff values('st06','George,Eddie');

insert into staff values('st07','Columbus,Chris');

insert into staff values('st08','Dobson,Frank');

insert into staff values('st09','Potter,Beatrix');

insert into staff values('st10','O`Zone,Zero');

insert into staff values('st11','Cantona,Eric');
